### ISSUE TITLE
The results of direct training with your model do not converge

### ISSUE THREAD

**Issue by zongyuyilang123** [erizmr/UnLiteFlowNet-PIV#4]
The results of direct training with your model do not converge,I do not know why
![This is an image](https://p.qlogo.cn/qqmail_head/ajNVdqHZLLCicVV66gUiaGMrW0MbGFdibuysZp3CmsJcpibaDErLLLGPJib2vHapibQXaQricabBLwEb2Q/0)

**Comment by erizmr** [comment]
Hi @zongyuyilang123 , could you please provide more details about how you set up the experiments? i.e., parameters, datasets etc.

**Comment by zongyuyilang123** [comment]
> Hi @zongyuyilang123 , could you please provide more details about how you set up the experiments? i.e., parameters, datasets etc.

Thank you very much,I have solved this problem.I wrongly added 
`with torch.no_grad(): `
for tensorFlow of three modules on line 532 in models.py
In addition,I want to say: your work is excellent!
